name: Publish on Pull Request

on: [push, workflow_dispatch]

jobs:
  pr_build:
    name: Push to Expo Go on Pull Requests
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: example-expo
      EXPO_PROJECT: "@daniel_grychtol/expo-bb-tech"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install YARN
        run: npm -g install yarn
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: false
          expo-version: 4.x
      - name: Install packages
        run: yarn install
      - name: EXPO Publish
        run: expo publish --non-interactive --release-channel ${{ env.PR_BRANCH }}
      - name: Add Comment To PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## 🚀 📲 Application preview:
            ### Scan with your mobile:
            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/${{ env.EXPO_PROJECT }}?release-channel=${{ env.PR_BRANCH }})
            ### or visit this link:
            Published to https://exp.host/${{ env.EXPO_PROJECT }}?release-channel=${{ env.PR_BRANCH }}
